const net = require('node:net');
const crypto = require('node:crypto');


main();

async function main(){

    const host = "example.com"
    const port = 443;

    const client = net.createConnection({ host, port }, () => {
        console.log(`Connected to ${host}:${port}`);
        const handshakeMessage = BuildHandshake(host);
        client.write(handshakeMessage);
    });

    client.on('data', (data) => {
        console.log(data.toString('hex'));
        // Process the received data as needed
    });
}


function buildClientHelloPayload(targetHost) {

    // === Version ===
    // This value means TLS 1.2, the reason why we use 0x3 0x3 is because of this table
    // | TLS Version | Hex |
    // |-------------|-----|
    // | SSL 3.0     | 0x3 0x0 |
    // | TLS 1.0     | 0x3 0x1 |
    // | TLS 1.1     | 0x3 0x2 |
    // | TLS 1.2     | 0x3 0x3 |
    // | TLS 1.3     | 0x3 0x4 |

    const version = [0x03, 0x03];
    const versionBuffer = Buffer.from(version);

    // === Random ===
    // A random 32-byte value generated by the client, used in the later key exchange process
    const random = crypto.randomBytes(32);
    const randomBuffer = Buffer.from(random);

    // === Session ID ===
    // 1 byte length + 32 bytes of random data
    // First byte present the length of the session ID, which is 32 bytes in this case
    // And the rest bytes are just random data
    const sessionIdLength = 32;
    const sessionId = crypto.randomBytes(sessionIdLength);
    const sessionIdBuffer = Buffer.concat([Buffer.from([sessionIdLength]), sessionId]);

    // === Cipher Suites ===
    // This means the cipher suite that client supports.
    // The first 2 bytes mean the length of the cipher suites list, in this case 4 bytes.
    // The rest bytes are the cipher suites ID, the first byte can be acknowledged as the cipher version,
    // and the second byte means the encryption algorithm, detail can be found in the link below
    // https://datatracker.ietf.org/doc/html/rfc5246#appendix-A.5
    const cipherSuites = [
        0x00, 0x3D, // TLS_RSA_WITH_AES_256_CBC_SHA256
        0x00, 0x6B  // TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
    ];
    const cipherSuitesLength = cipherSuites.length;
    const cipherSuitesLengthBuffer = toUint16BE(cipherSuitesLength);
    const cipherSuitesBuffer = Buffer.concat([
        Buffer.from(cipherSuitesLengthBuffer), 
        Buffer.from(cipherSuites)
    ]);

    // === Compression Methods ===
    // This means the compression methods that client supports.
    // The first byte means the length of the compression methods list, in this case 1 byte.
    const compressionMethods = [0x00]; // null compression
    const compressionMethodsLength = compressionMethods.length;
    const compressionMethodsLengthBuffer = toUint8BE(compressionMethodsLength);
    const compressionMethodsBuffer = Buffer.concat([
        Buffer.from(compressionMethodsLengthBuffer),
        Buffer.from(compressionMethods)
    ]);

    // === Extensions ===
    // The first two bytes mean the total length of the extensions, and the rest bytes are the extensions data.
    //Extensions are defined in IANA Transport Layer Security (TLS) 

    // --- Extensions 

    // >>> SNI (Server Name Indication) ---
    // This extension is used to indicate the hostname.
    // The row of the bytes means the total data length of the extension, which is
    // type byte (1) + hostname length bytes (2) + hostname bytes (hostname.length)

    const sniExtensionsType = [0x00, 0x00];
    const nameType = [0x00];
    const hostname = targetHost;

    const hostnameBuffer = Buffer.from(hostname);
    const hostnameLength = toUint16BE(hostname.length);

    const serverNameEntry = Buffer.concat([
        Buffer.from(nameType),
        Buffer.from(hostnameLength),
        hostnameBuffer
    ]);
    
    const sniListLength = toUint16BE(serverNameEntry.length);
    const sniExtensionData = Buffer.concat([
        sniListLength,
        serverNameEntry
    ]);

    const sniExtensionLength = toUint16BE(sniExtensionData.length);
    const sniExtensionBuffer = Buffer.concat([
        Buffer.from(sniExtensionsType),
        Buffer.from(sniExtensionLength),
        sniExtensionData
    ]); // [2x type][2x length][2x listLength][nameType][2x hostnameLength][hostname...]

    // >>> Supported Groups ---
    // This extension is used to indicate the supported groups (elliptic curves) that client supports.
    // The first two bytes mean the total length of the extension, and the rest bytes are the extension data.

    const supportedGroupsExtensionsType = [0x00, 0x0A];
    const supportedGroups = [
        0x00, 0x1D, // x25519
        0x00, 0x17, // secp256r1
        0x00, 0x18  // secp384r1
    ];
    const supportedGroupBufferList = Buffer.from(supportedGroups);
    const supportedGroupsLength = toUint16BE(supportedGroupBufferList.length);
    const supportedGroupData = Buffer.concat([
        supportedGroupsLength,
        supportedGroupBufferList
    ]);

    const supportedGroupsPayloadLength = toUint16BE(supportedGroupData.length);
    const supportedGroupsBuffer = Buffer.concat([
        Buffer.from(supportedGroupsExtensionsType),
        Buffer.from(supportedGroupsPayloadLength),
        supportedGroupData
    ]);//[2x type][2x payloadLength][2x groupLength][supportedGroups...]

    // >>> EC Point Formats ---
    // This extension is used to indicate the supported EC point formats that client supports.
    // The first two bytes mean the total length of the extension, and the rest bytes are the extension data.

    const ecPointFormatsExtensionsType = [0x00, 0x0B];
    const ecPointFormats = [0x00];
    const ecPointFormatsLength = toUint8BE(ecPointFormats.length);
    const ecPointFormatData = Buffer.concat([
        ecPointFormatsLength,
        Buffer.from(ecPointFormats)
    ]);

    const ecPointFormatsPayloadLength = toUint16BE(ecPointFormatData.length);
    const ecPointFormatsBuffer = Buffer.concat([
        Buffer.from(ecPointFormatsExtensionsType),
        Buffer.from(ecPointFormatsPayloadLength),
        ecPointFormatData
    ]);// [2x type][2x payloadLength][1x pointFormatLength][ecPointFormats...]

    // >>> Signature Algorithms ---
    // This extension is used to indicate the supported signature algorithms that client supports.
    // The first two bytes mean the total length of the extension, and the rest bytes are the extension data.

    const signatureAlgorithmsExtensionsType = [0x00, 0x0D];
    const signatureAlgorithms = [
        0x04, 0x03, // ecdsa_secp256r1_sha256
        0x04, 0x01 // rsa_pkcs1_sha256
    ];
    const signatureAlgorithmsLength = toUint16BE(signatureAlgorithms.length);
    const signatureAlgorithmsData = Buffer.concat([
        signatureAlgorithmsLength,
        Buffer.from(signatureAlgorithms)
    ]);

    const signatureAlgorithmsPayloadLength = toUint16BE(signatureAlgorithmsData.length);
    const signatureAlgorithmsBuffer = Buffer.concat([
        Buffer.from(signatureAlgorithmsExtensionsType),
        Buffer.from(signatureAlgorithmsPayloadLength),
        signatureAlgorithmsData
    ]);// [2x type][2x payloadLength][2x signatureAlgorithmsLength][signatureAlgorithms...]

    // ---------

    const extensionsPayload = Buffer.concat([
        sniExtensionBuffer,
        supportedGroupsBuffer,
        ecPointFormatsBuffer,
        signatureAlgorithmsBuffer
    ]);

    const extensionsLength = toUint16BE(extensionsPayload.length);
    const extensionsBuffer = Buffer.concat([
        Buffer.from(extensionsLength),
        extensionsPayload
    ]);// [2x extensionsLength][extensionsPayload...]

    // === Payload ===
    return Buffer.concat([
        versionBuffer,
        randomBuffer,
        sessionIdBuffer,
        cipherSuitesBuffer,
        compressionMethodsBuffer,
        extensionsBuffer
    ]);

    // + [version] 2 bytes
    //
    // + [random] 32 bytes
    //
    // + [sessionIdLength] 1 byte
    // + [sessionId] 32 bytes
    //
    // + [cipherSuitesLength] 2 bytes
    // + [cipherSuites]
    // 
    // + [compressionMethodsLength] 1 byte
    // + [compressionMethods]
    // 
    // + [extensionsLength] 2 bytes
    // + [extensionsPayload]
}

function BuildHandshake(host) {

    const handshake = Buffer.from([0x01]); // Handshake Type: Client Hello
    const bodyLength = Buffer.alloc(3);
    const clientHelloPayload = buildClientHelloPayload(host);
    bodyLength.writeUIntBE(clientHelloPayload.length, 0, 3);

    const handshakeMessage = Buffer.concat([
        handshake,
        bodyLength,
        clientHelloPayload
    ]);

    const recordType = Buffer.from([0x16]); // Record Type: Handshake
    const version = Buffer.from([0x03, 0x03]);
    const recordLength = Buffer.alloc(2);
    recordLength.writeUInt16BE(handshakeMessage.length, 0);

    const tlsRecord = Buffer.concat([
        recordType,
        version,
        recordLength,
        handshakeMessage
    ]);

    return tlsRecord;

}

function toUint16BE(value) {
    const buffer = Buffer.alloc(2);
    buffer.writeUInt16BE(value, 0);
    return buffer;
}

function toUint8BE(value) {
    const buffer = Buffer.alloc(1);
    buffer.writeUInt8(value, 0);
    return buffer;
}